//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizwheel2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRG522SA2021Entities : DbContext
    {
        public PRG522SA2021Entities()
            : base("name=PRG522SA2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<KeyValuePair>().HasKey(x => x.Key);
			base.OnModelCreating(modelBuilder, null);
        }
    
        public virtual DbSet<BizDataB> BizDataBs { get; set; }
    }
}
